export const CONFIG_DEFAULTS = {
  AUTO: 'Auto',
  BACKGROUND_COLOR: 'BackgroundColor',
  BANNER: 'Banner',
  BATCH_SIZE: 'BatchSize',
  CANVAS_CONTEXT: 'CanvasContext',
  CANVAS: 'Canvas',
  DEFAULT_ORIGIN: 'DefaultOrigin',
  GLOBAL_VAR: 'GlobalVar',
  MAX_TEXTURES: 'MaxTextures',
  PARENT: 'Parent',
  RENDERER: 'Renderer',
  SCENES: 'Scenes',
  SIZE: 'Size',
  WEBGL_CONTEXT: 'WebGLContext',
  WEBGL: 'WebGL',
};
